export const CONTRACT_ADDRESS = 'ST165VYJW96ZDG3YBQQZDNBPCB1YW8WGH7S9K1XM6';
export const CONTRACT_NAME = 'gsupply';

export const ROLES = {
  MANUFACTURER: 0,
  DISTRIBUTOR: 1,
  RETAILER: 2,
  CONSUMER: 3
};

export const STAGES = {
  ORIGIN: 0,
  MANUFACTURING: 1,
  DISTRIBUTION: 2,
  RETAIL: 3,
  CONSUMER: 4
};
