export const CONTRACT_ADDRESS = 'YOUR_CONTRACT_ADDRESS';
export const CONTRACT_NAME = 'YOUR_CONTRACT_NAME';

export const ROLES = {
  MANUFACTURER: 0,
  DISTRIBUTOR: 1,
  RETAILER: 2,
  CONSUMER: 3
};

export const STAGES = {
  ORIGIN: 0,
  MANUFACTURING: 1,
  DISTRIBUTION: 2,
  RETAIL: 3,
  CONSUMER: 4
};
